### ISSUE TITLE
Can't run this project in Entitas 0.3x.x

### ISSUE THREAD

**Issue by TokyoDan** [JamesMcMahon/entitas-2d-roguelike#1]
I tried using the MigrationAssistant.exe but when I run the project I get this error:

`IndexOutOfRangeException: Array index is out of range.
Entitas.Unity.VisualDebugging.HierarchyIconEditor.get_hierarchyIcon () (at Assets/Libraries/Entitas.Unity.VisualDebugging/Editor/HierarchyIconEditor.cs:11)
Entitas.Unity.VisualDebugging.HierarchyIconEditor.onHierarchyWindowItemOnGUI (Int32 instanceID, Rect selectionRect) (at Assets/Libraries/Entitas.Unity.VisualDebugging/Editor/HierarchyIconEditor.cs:38)
UnityEditor.SceneHierarchyWindow.OnGUIAssetCallback (Int32 instanceID, Rect rect) (at C:/buildslave/unity/build/Editor/Mono/SceneHierarchyWindow.cs:379)
UnityEditor.TreeView.DoItemGUI (UnityEditor.TreeViewItem item, Int32 row, Single rowWidth, Boolean hasFocus) (at C:/buildslave/unity/build/Editor/Mono/GUI/TreeView/TreeView.cs:441)
UnityEditor.TreeView.IterateVisibleItems (Int32 firstRow, Int32 numVisibleRows, Single rowWidth, Boolean hasFocus) (at C:/buildslave/unity/build/Editor/Mono/GUI/TreeView/TreeView.cs:568)
UnityEditor.TreeView.OnGUI (Rect rect, Int32 keyboardControlID) (at C:/buildslave/unity/build/Editor/Mono/GUI/TreeView/TreeView.cs:504)
UnityEditor.SceneHierarchyWindow.DoTreeView (Single searchPathHeight) (at C:/buildslave/unity/build/Editor/Mono/SceneHierarchyWindow.cs:505)
UnityEditor.SceneHierarchyWindow.OnGUI () (at C:/buildslave/unity/build/Editor/Mono/SceneHierarchyWindow.cs:320)
System.Reflection.MonoMethod.Invoke (System.Object obj, BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) (at /Users/builduser/buildslave/mono/build/mcs/class/corlib/System.Reflection/MonoMethod.cs:222)
`

**Comment by JamesMcMahon** [comment]
I think `MigrationAssistant.exe` is mostly likely failing since the version of Entitas in this project predates the automatic migration by a few release. 

The project needs to be manually migrated over to the new version. It's on my TODO list but I am finishing up a commercial game right now so it may be a little before I get to it.

However, it should work as is with the included version of Entitas.

**Comment by JamesMcMahon** [comment]
Should be fix in https://github.com/JamesMcMahon/entitas-2d-roguelike/commit/cdbdd59c92b28b4d453da823b848318b8c3d8cf5
