### ISSUE TITLE
Entitas 0.42.3 compatibility

### ISSUE THREAD

**Issue by itsmylife** [JamesMcMahon/entitas-2d-roguelike#2]
It would be great if you upgrade the project to Entitas 0.42.3

Thank you for that great work.

**Comment by JamesMcMahon** [comment]
Hey,

I'm taking a look at upgrading it. There have been a lot of API revisions so might be a little bit.

The upgrade to 0.36.0 is kind of pain and I am working through some issues.

**Comment by itsmylife** [comment]
Hey! 

Thank you for that. I hope it will not give much pain. As you mentioned there are a lot of chanings. 

Looking forward the upgrade.

**Comment by JamesMcMahon** [comment]
All done, https://github.com/JamesMcMahon/entitas-2d-roguelike/commit/768d9a9d7d8d4647ca1ce8416826bf6a2754f91c!

Quite the breaking API journey. I was mostly focusing on getting things working, could probably use a best practices pass. I'm open to any pull requests to improve the project or help me stay on top on Entitas.

**Comment by itsmylife** [comment]
Thank you very much James. I did not find time to take a look because of the moving another country. But I am really appreciated about what you did. Thanks!
